apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-spring-app
  labels:
    app: demo-spring-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-spring-app
  template:
    metadata:
      labels:
        app: demo-spring-app
    spec:
      containers:
      - name: demo-spring-app
        image: registry.cn-hongkong.aliyuncs.com/waltertest/waltertest
        ports:
        - containerPort: 8080